config/routes.rb
Rails.application.routes.draw do
  root to: 'flights#index'
  resources :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/spreedly.rb
require 'pp'
require 'json'
require 'uri'
require 'net/http'

ENV_KEY      = Rails.configuration.spreedly['environment_key']
ACCESS_SECRET = Rails.configuration.spreedly['access_secret']
GATEWAY_TOKEN = Rails.configuration.spreedly['gateway_token']

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flights = Flight.all 
	end

	def show
		@flight = Flight.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/index.html.erb
<h1>All Flights</h1>

<ul id="flights">
	<% @flights.each do |flight| %>
		<li>
				From: <%= flight.origin %> 
				To: <%= flight.destination %> 
				Price: <%= link_to flight.price, '#', class: "price" %>
		</li>
	<% end %>
</ul>

<p class="text"></p>

app/views/flights/show.html.erb
<p>Origin: <%= @flight.origin %></p>
<p>Destination: <%= @flight.destination %></p>
<p>Price: <%= @flight.price %></p>
<%= link_to "<< Back to Flights List", flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreedlyAirlines2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://core.spreedly.com/iframe/express-2.min.js"></script>
    <%= yield %>
  </body>
</html>